import{test} from "@playwright/test"
import { login } from "../utils/login";
import { log } from "console";
test('Delete user', async({page})=> {
  await login (page);
  await page.getByRole('button', { name: 'User Management' }).click();
 await page.getByRole('row', { name: 'Marketing Team Market Planning TSM NCR airtel one HVSO97HB 4000000001 ao12@' }).getByRole('img').click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Existing User' }).click();
  await page.locator('.css-hlgwow').first().click();
  await page.getByRole('option', { name: 'test tsm play' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'test tsm play' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(5) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'test tsm play' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.waitForTimeout(5000);
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'test tsm play' }).click();
  await //page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 2' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 3' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 4' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 5' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('table').locator('div').filter({ hasText: '25 results available.Use Up' }).locator('div').nth(3).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow').click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 6' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 7' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('#react-select-209-placeholder').click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByText('Completed Orders').click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 2' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 3' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 4' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 5' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByText('Recently Deleted').click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 2' }).click();
  await page.locator('.css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('.css-wb75yw-control > .css-hlgwow > .css-194vhft').first().click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('#react-select-273-placeholder').click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.locator('tr:nth-child(10) > td:nth-child(7) > .css-b62m3t-container > .css-wb75yw-control > .css-hlgwow > .css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Go to page 3' }).click();
  await page.locator('.css-194vhft').click();
  await page.getByRole('option', { name: 'airtel one' }).click();
  await page.getByRole('button', { name: 'Assign' }).click();
});